name: 2019 - Tests (py)

on:
  push:
    paths:
      - 2019/**
      - .github/workflows/2019*
env:
  PYTHON_VERSION: 3.9
  YEAR: 2019

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: pip install -r requirements.txt -r requirements_dev.txt
        working-directory: ./${{ env.YEAR }}

      - name: Lint
        run: make lint
        working-directory: ./${{ env.YEAR }}

      - name: Test
        run: make test
        working-directory: ./${{ env.YEAR }}
